# Generated by Django 3.2.20 on 2023-09-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_school',
            name='district',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user_profile_school',
            name='mentor',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user_profile_school',
            name='principal',
            field=models.CharField(default='', max_length=100),
        ),
    ]
