# Generated by Django 3.2.17 on 2023-06-19 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackstudent',
            old_name='student_id',
            new_name='student',
        ),
    ]
