# Generated by Django 3.2.20 on 2023-09-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230918_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_school',
            name='logo',
            field=models.ImageField(default='', upload_to='logo'),
        ),
    ]
