# Generated by Django 3.2.17 on 2023-06-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_student_id_feedbackstudent_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstudent',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationstudent',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
