# Generated by Django 3.2.20 on 2023-09-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_school_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile_school',
            name='logo',
            field=models.ImageField(default='', upload_to='logo/'),
        ),
    ]
