# Generated by Django 3.2.17 on 2023-06-22 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_notificationstudent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationstudent',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
