# Generated by Django 4.2.3 on 2023-10-10 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_profile_school_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPrincipal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_profile_principal')),
            ],
        ),
    ]
