# Generated by Django 4.2.3 on 2023-10-10 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_notificationprincipal'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackPrincipal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.TextField()),
                ('feedback_reply', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_profile_principal')),
            ],
        ),
    ]
