# Generated by Django 4.2.3 on 2023-10-10 14:06

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_feedbackprincipal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_principal',
            name='marks_obtained',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_profile_principal',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to=users.models.save_profile_image, verbose_name='Profile Image'),
        ),
    ]
