# Generated by Django 4.2.3 on 2023-10-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_profile_principal_marks_obtained_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile_principal',
            name='marks_obtained',
        ),
    ]
