# Generated by Django 3.2.20 on 2023-08-12 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_notificationstudent_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationstudent',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_profile_student'),
        ),
    ]
