# Generated by Django 3.2.20 on 2023-12-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_student',
            name='section',
            field=models.CharField(default='', max_length=50),
        ),
    ]
