# Generated by Django 3.2.20 on 2023-08-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_feedbackschool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackschool',
            old_name='student',
            new_name='school',
        ),
    ]
