# Generated by Django 4.2.3 on 2023-10-11 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_notificationteacher_feedbackteacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user_profile_teacher'),
        ),
    ]
