# Generated by Django 3.2.20 on 2023-12-11 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_user_profile_student_section'),
        ('users', '0010_alter_feedbackteacher_teacher'),
    ]

    operations = [
    ]
