# Generated by Django 4.2.3 on 2023-11-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_school'),
        ('users', '0010_alter_feedbackteacher_teacher'),
    ]

    operations = [
    ]
