# Generated by Django 4.2.3 on 2023-12-12 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_0007_school_0010_alter_feedbackteacher_teacher'),
        ('users', '0011_merge_20231211_0948'),
    ]

    operations = [
    ]
