# Generated by Django 3.2.20 on 2023-08-16 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile_student',
            name='marks_obtained',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Marks',
        ),
    ]
