# Generated by Django 3.2.20 on 2023-09-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicwise_marks',
            name='new_marks',
        ),
        migrations.AlterField(
            model_name='topicwise_marks',
            name='marks',
            field=models.CharField(default=0, max_length=500),
        ),
    ]
