# Generated by Django 3.2.17 on 2023-06-08 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='ppt',
        ),
        migrations.AddField(
            model_name='lesson',
            name='assessment',
            field=models.URLField(default='', max_length=300, verbose_name='Assessment'),
        ),
    ]
