# Generated by Django 3.2.20 on 2023-08-10 15:49

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanzo_model_name',
            name='file',
            field=models.FileField(blank=True, upload_to=curriculum.models.save_mechanzo_file, verbose_name='Mechanzo'),
        ),
    ]
