# Generated by Django 3.2.17 on 2023-06-08 11:25

import curriculum.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_auto_20230608_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='assessment',
        ),
        migrations.AddField(
            model_name='lesson',
            name='ppt',
            field=models.FileField(blank=True, upload_to=curriculum.models.save_lesson_files, verbose_name='Presentations'),
        ),
    ]
