# Generated by Django 3.2.20 on 2023-12-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_lecturerating'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='assessment',
            field=models.URLField(default='', max_length=300, verbose_name='Assessment'),
        ),
    ]
